### ISSUE TITLE
no default export reported by NextJS

### ISSUE THREAD

**Issue by ericvrp** [jimmycallin/react-hook-videojs#1]
I'm getting this error in NextJS

Attempted import error: 'react-hook-videojs' does not contain a default export (imported as 'useVideoJS').

**Comment by jimmycallin** [comment]
Hi @ericvrp, sorry I didn't see your issue until now.

The README was incorrect, thanks for notifying me about this. The import statement should be:

```
import { useVideoJS } from "react-hook-videojs";
```

This is fixed now.
