### ISSUE TITLE
How to custom event callbacks?

### ISSUE THREAD

**Issue by leopku** [jimmycallin/react-hook-videojs#131]
First of all, thanks for this awesome library.

I am troubling when I wanna making the player toggle to fullscreen mode.

How can I add a callback like

```js
player.on('play', () => console.log('now playing...'));
```

**Comment by jimmycallin** [comment]
Hi!

The videojs `player` object is returned when calling `useVideoJs()`, so you should be able to do something like this:

```
const { Video, player, ready } = useVideoJS(
    { sources: [{ src: videoUrl }] }  );
  if (ready) {
     player.on('play', () => console.log('now playing...'));
  }
```

Let me know if this isn't working for you!

**Comment by leopku** [comment]
It works.
Big thanks.
