### ISSUE TITLE
Allowing for sharing vjs state around an app in an ergonomic way

### ISSUE THREAD

**Issue by narthur** [jimmycallin/react-hook-videojs#156]
The project I'm working on has this interface:

![Screen Shot 2022-07-18 at 8 37 12 AM](https://user-images.githubusercontent.com/4655422/179512654-7871bc15-b142-4589-886f-2f6e771267c2.png)

Basically, each recording detail page has its own player and custom controls UI. In addition, if you've begun playing the media on a detail page, the media should continue playing in the miniplayer if you navigate away from the detail page, opening the miniplayer if it isn't already opened.

What this basically means is that we have to end up moving videojs playback around the page using refs.

I would like to be able to access videojs state using specific hooks to subscribe to videojs internal state. For example, a pause button component could use a hook for subscribing to paused state:

```
const [paused, setPaused] = usePaused(); 
```

I'm thinking we'd have hooks for lots of different videojs state variables:

- usePaused
- useDuration
- useTime
- useSources
- useFullscreen
- useSpeed
- ... etc

Each hook would subscribe to the appropriate videojs events to provide up-to-date data for each property, and trigger rerenders appropriately for hook users.

In order to avoid the need to identify the applicable recording for each such hook, I'd like to be able to surround the detail page with a provider that specifies this for me:

```
<VideoJsProvider videoJsOptions={...}>
  ...
  const { Video, player, ... } = useVideoJs();
  ...
  <PauseButton />
  <Timestamp />
  ...
</VideoJsProvider>
```

I'm less certain what my desired API would look like for the miniplayer. Basically I want to have the ability to capture whatever the currently playing media is and use that inside the miniplayer.

Note that the miniplayer will never be displaying the video at the same time that the detail page is displaying that video--so the actual videojs html component only needs to be in one place at a time. It's when the user navigates away from the detail page that the video player would be handed off to the miniplayer.

But the details and controls in the miniplayer should hook up to the currently playing media regardless.

I don't know if it would be something like this for the miniplayer, where failing to provide videojsoptions results in connecting to global state?:

```
<VideoJsProvider>
    ...
  const { Video, player, ... } = useVideoJs();
  ...
  <Video enabled={false} />
  <PauseButton />
  <Timestamp />
  ...
</VideoJsProvider>
```

And at that point, perhaps flipping `enabled` to `true` would result in the videojs element being moved (outside of react using dom manipulation) from the origin player to the destination player.

Is there a more intuitive way to expose this kind of behavior?

**Comment by jimmycallin** [comment]
Hello!

Interesting use case! I think adding hooks for each state variable is a bit out of scope for this library, as the API is fairly minimal, as it might become difficult to maintain as videojs updates its library. If you look at the implementation, it really doesn't do much that requires additional maintainance as video.js changes, and I would very much prefer to keep it on this level. :)

That said, there is nothing stopping you from implementing these hooks yourself. I believe the VideoJsProvider you are describing should be fairly easy to implement:


```
export const VideoJsContext = createContext(null);

export function usePaused() {
  const videojs = useContext(VideoJsContext);
  const [paused, setPaused] = useState(videojs.paused());
  const onPause = () => setPaused(true);
  const onPlay = () => setPaused(false);
  handlePause(pause) {
    if (pause) {
        videojs.pause();
    } else {
        videojs.play();
    }
  }
  
  useEffect(() => {
    videojs.on("pause", onPause);
    videojs.on("play", onPlay);
    return () => {
      videojs.off("pause", onPause);
      videojs.off("play", onPlay);
    };
  }, []);

  return [paused, handlePause];
}

export function VideoJsProvider({ videoJsOptions, children }) {
  const videoJs = useVideoJs(videoJsOptions);

  return (
    <VideoJsContext.Provider value={videojs}>
      {children}
    </VideoJsContext.Provider>
  );
}
```

This way you can import the usePaused function and use it anywhere within the context provided by VideoJsProvider. You can also always get the videojs instance by importing the videojs context.

Regarding the miniplayer I'm less certain how to solve this cleanly. I would look into using the `React.createPortal` to render it to a node outside of the tree, and perhaps update which DOM node it renders to given some sort of trigger. You might run into issues where it reinitializes on change, but should be solvable by using React.memo I think. Does this make sense?

**Comment by narthur** [comment]
@jimmycallin Makes complete sense--really appreciate the clarity. I've decided to go ahead and build my own library:

https://github.com/narthur/react-videojs-hooks

Appreciate your help thinking this through!
